language: python

python:
  - "3.7"

services:
  - docker

env:
  #scripts dir host and docker
  SCRIPTS_DIR: tests
  DOCKER_SCRIPTS_DIR: /home/dev/scripts

  #server on host
  SERVER: "localhost:8080"
  EUREKA_SERVER: "http://localhost:8081/eureka/v2"

  # unit tests env vars
  TEMPLATES_DIR: inputs/templates
  VARS_DIR: inputs/variables

  #deployment
  MAX_DEPLOY_MEMORY: 80
  MAX_DEPLOYMENTS: 3

  NGROK_TOKEN: 1RER6BUC3QNNwYWY5LcIBjrv3A8_24QccmopTEQJGMErG9uzw

before_install:
  - docker pull alpine:3.9.4
  - docker pull mysql:5.6
  - docker pull dinutac/estuary-testrunner:latest
  - docker pull dinutac/netflixoss-eureka:1.9.13
  - chmod +x ngrok.sh
  - docker build -t dinutac/estuary-deployer:latest .

install:
  - pip install -r requirements.txt

before_script:
  - py.test $SCRIPTS_DIR/render_test.py --cov=entities

script:
  #run functional testrunner integration API tests
  - docker network create estuarydeployer_default
  - docker run -d
    -p 8081:8080 dinutac/netflixoss-eureka:1.9.13
  - IP_ADDR_STRING=$(hostname -I)
  - IP_ADDR_ARRAY=($IP_ADDR_STRING)
  - echo "EUREKA_SERVER=http://${IP_ADDR_ARRAY[0]}:8081/eureka/v2" >> .env
  - echo "APP_IP_PORT=${IP_ADDR_ARRAY[0]}:8080" >> .env
  - cat .env
  - chmod +x wait-for-it.sh
  - ./wait-for-it.sh -t 20 "http://${IP_ADDR_ARRAY[0]}:8081/eureka/v2" -- echo "eureka running" && sleep 30
  - docker run -d
    -e MAX_DEPLOY_MEMORY=80
    -p 8080:8080
    -v $PWD/inputs/templates:/data
    -v $PWD/inputs/variables:/variables
    -v /var/run/docker.sock:/var/run/docker.sock
    --net=estuarydeployer_default
    --name estuary-deployer
    --env-file .env
    dinutac/estuary-deployer:latest

  #  - docker network ls
  #  - echo "Deployer net is $(docker network ls | grep deployer | awk '{print $2}' | head -1)"
  - sleep 10
  - docker ps -a
  - python3 -m unittest discover $SCRIPTS_DIR/rest_testrunner_integration "*_test.py"
  - docker ps -a
  #  - ./ngrok.sh
  #  - docker logs -f estuary-deployer
  #  - docker logs $(docker ps -a | grep testrunner | awk '{print $13}')
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker network prune -f

  #run unit tests on travis vm and on docker
  - docker network create estuarydeployer_default
  - docker run -d
    -e MAX_DEPLOY_MEMORY=$MAX_DEPLOY_MEMORY
    -e MAX_DEPLOYMENTS=$MAX_DEPLOYMENTS
    -p 8080:8080
    -v $PWD/inputs/templates:/data
    -v $PWD/inputs/variables:/variables
    -v /var/run/docker.sock:/var/run/docker.sock
    --net=estuarydeployer_default
    --name estuary-deployer
    dinutac/estuary-deployer:latest
  - sleep 10
  - python3 -m unittest discover $SCRIPTS_DIR "render_test.py"
  - python3 -m unittest discover $SCRIPTS_DIR/rest_docker "*_test.py"
  - docker exec estuary-deployer python3 -m unittest discover $DOCKER_SCRIPTS_DIR "render_test.py"
  #  - docker logs estuary-deployer
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker network prune -f

  #run functional rest API tests without docker sock mount
  - docker network create estuarydeployer_default
  - docker run -d
    -e MAX_DEPLOY_MEMORY=80
    -p 8080:8080
    -v $PWD/inputs/templates:/data
    -v $PWD/inputs/variables:/variables
    --net=estuarydeployer_default
    --name estuary-deployer
    dinutac/estuary-deployer:latest
  - sleep 5
  - python3 -m unittest discover $SCRIPTS_DIR/rest_docker_sock "*_test.py"
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker network prune -f

  #run eureka registration tests
  - docker-compose up -d
  - sleep 45
  - docker ps
  - docker exec estuary-deployer python3 -m unittest discover $DOCKER_SCRIPTS_DIR/tests/rest_eureka "*_test.py"
  - docker-compose down -v

  # run clean_folder scheduler
  - docker-compose up -d
  - docker ps
  - docker exec estuary-deployer python3 -m unittest discover $DOCKER_SCRIPTS_DIR/tests/clean_folder_scheduler "*_test.py"
  - docker-compose down -v

  # run env_expire scheduler
  - docker-compose up -d
  - sleep 45
  - docker ps
  - docker exec estuary-deployer python3 -m unittest discover $DOCKER_SCRIPTS_DIR/tests/env_expire_scheduler "*_test.py"
  - docker-compose down -v

  #check template render
  - docker run -i
    -v $TRAVIS_BUILD_DIR/inputs/templates:/data
    -v $TRAVIS_BUILD_DIR/inputs/variables:/variables  -e TEMPLATE=standalone.yml
    -e VARIABLES=variables.yml -e DATABASE=mysql56 -e IMAGE=latest --entrypoint python3 dinutac/estuary-deployer:latest
    $DOCKER_SCRIPTS_DIR/main.py

  #check template render
  - docker run --entrypoint jinja2
    -v $TRAVIS_BUILD_DIR/inputs/templates:/data
    -v $TRAVIS_BUILD_DIR/inputs/variables:/variables
    dinutac/estuary-deployer:latest
    /data/json.j2 /variables/json.json --format=json

after_success:
  - coveralls


