version: "3.3"

services:
  estuary-deployer:
    container_name: estuary-deployer
    image: dinutac/estuary-deployer:latest
    hostname: estuary-deployer
    entrypoint: python3 /home/dev/scripts/main_flask.py
#    entrypoint: tail -f /etc/alpine-release
    environment:
      limit: 'sky' #example env var inserted. you can read it with environ('limit')
      MAX_DEPLOY_MEMORY: 80 #% from total. tune this parameter after you measure how much a docker compose env consumes. E.g. 16 GB memory => docker will use up to ~13GB.)
    volumes:
      - ./inputs/templates:/data
      - ./inputs/variables:/variables
      - ./:/home/dev/scripts/
      - /var/run/docker.sock:/var/run/docker.sock #works on win also as long as you don't enable tcp daemon on 2375/2376
      - ./tmp:/tmp
#      - /etc/hostname:/etc/hostname #for hostname
    ports:
      - "8080:8080"

    expose:
      - "8080"
