kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: estuary-deployer
  name: estuary-deployer
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    k8s-app: estuary-deployer
