kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: estuary-deployer
  name: estuary-deployer-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: estuary-deployer
