version: '2.2'
services:
  mysql561:
    restart: always
    image: mysql:5.6
    hostname: mysql561
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'testing'

    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
#    volumes:
#      - ./mysqlcnf:/etc/mysql/conf.d/

#no jinja2 code. just for service deployer testing